# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: d9e523cc4a81743c6af5f5132cd893bfccb59632fd075e9545bb23f749a08ae87dcf1de152e72fead9523e800b00be4332b4b4abd7e7eb14d20429a43546bd4b

test:
  secret_key_base: 1152b6dc54ce0a193019cbb4d070e8732dcba435fa8a4db8d1286403a7c860e74460d2c0eb10b6d7dba4fb0cbd27d5e784ff4f897a55cb5638d44fe3274ec33e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
